name: "kibana"

dep:

env:
  default:
    NAME: "kibana"
  imm_dev_hl:
    NAMESPACE: "imm-dev-hl"
    K8S_CONTEXT: "weboffice-hl-2"

task:
  install:
    step:
      - test "${K8S_CONTEXT}" == "$(kubectl config current-context)" || exit 1
      - helm repo add elastic https://helm.elastic.co
      - |
        helm install -n "${NAMESPACE}" "${NAME}" elastic/kibana \
          --set image=docker.elastic.co/kibana/kibana \
          --set imageTag=7.9.0 \
          --set elasticsearchHosts=http://elasticsearch-master:9200 \
          --set ingress.enabled=true \
          --set ingress.hosts[0].host=k8s.kibana.hatlonely.com \
          --set ingress.hosts[0].paths[0].path=/ \
          --set ingress.annotations."kubernetes\.io\/ingress\.class"=nginx \
          --set ingress.annotations."kubernetes\.io\/tls\-acme"="\"true\""
  delete:
    step:
      - test "${K8S_CONTEXT}" == "$(kubectl config current-context)" || exit 1
      - helm delete -n "${NAMESPACE}" "${NAME}"
