name: grafana

dep:

env:
  default:
  imm_dev_hl:
    NAME: "grafana"
    NAMESPACE: "imm-dev-hl"
    K8S_CONTEXT: "weboffice-hl-2"

task:
  install:
    step:
      - test "${K8S_CONTEXT}" == "$(kubectl config current-context)" || exit 1
      - helm repo add grafana https://grafana.github.io/helm-charts
      #- helm repo update
      - |
        helm install --verify=false -n "${NAMESPACE}" "${NAME}" grafana/grafana \
          --set ingress.enabled=true \
          --set ingress.hosts={k8s.grafana.hatlonely.com} \
          --set ingress.annotations."kubernetes\.io\/ingress\.class"=nginx \
          --set ingress.annotations."kubernetes\.io\/tls\-acme"="\"true\"" \
          --set "grafana\.ini".server.root_url="%(protocol)s://k8s.grafana.hatlonely.com"
      - kubectl get secret --namespace "${NAMESPACE}" "${NAME}" -o jsonpath="{.data.admin-user}" | base64 --decode ; echo
      - kubectl get secret --namespace "${NAMESPACE}" "${NAME}" -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
  delete:
    step:
      - helm delete -n "${NAMESPACE}" "${NAME}"