apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: prod
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: slow
  selector: