name: cert-manager

dep:

env:
  default:
  imm_dev_hl:
    NAME: "cert-manager"
    NAMESPACE: "cert-manager"
    K8S_CONTEXT: "weboffice-hl-2"

task:
  install:
    step:
      - test "${K8S_CONTEXT}" == "$(kubectl config current-context)" || exit 1
      - kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.2.0/cert-manager.crds.yaml
      - helm repo add jetstack https://charts.jetstack.io
      - helm repo update
      - kubectl create namespace cert-manager
      - |
        helm install -n "${NAMESPACE}" "${NAME}" jetstack/cert-manager \
          --set image.repository=quay.io/jetstack/cert-manager-controller \
          --set image.tag=v1.2.0 \
          --set ingressShim.defaultIssuerName=letsencrypt-prod \
          --set ingressShim.defaultIssuerKind=ClusterIssuer
  delete:
    step:
      - helm delete -n "${NAMESPACE}" "${NAME}"